import { useState, useEffect } from 'react';
import type { FC } from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faTimes } from '@fortawesome/free-solid-svg-icons';
import { Account, AccountType } from '../../models/Settings';
import { generateExportDisplayName } from '../../models/Settings';

interface AccountFormModalProps {
  account: Account | null;
  onSave: (data: {
    institutionName: string;
    accountName: string;
    exportDisplayName?: string;
    accountType?: AccountType;
  }) => void;
  onCancel: () => void;
}

const AccountFormModal: FC<AccountFormModalProps> = ({ account, onSave, onCancel }) => {
  const [institutionName, setInstitutionName] = useState('');
  const [accountName, setAccountName] = useState('');
  const [exportDisplayName, setExportDisplayName] = useState('');
  const [accountType, setAccountType] = useState<AccountType | ''>('');
  const [customExportName, setCustomExportName] = useState(false);
  const [errors, setErrors] = useState<{ institutionName?: string; accountName?: string }>({});

  // Initialize form when account changes
  useEffect(() => {
    if (account) {
      setInstitutionName(account.institutionName);
      setAccountName(account.accountName);
      setExportDisplayName(account.exportDisplayName);
      setAccountType(account.accountType || '');
      // Check if export name is custom (different from auto-generated)
      const autoGenerated = generateExportDisplayName(account.institutionName, account.accountName);
      setCustomExportName(account.exportDisplayName !== autoGenerated);
    } else {
      setInstitutionName('');
      setAccountName('');
      setExportDisplayName('');
      setAccountType('');
      setCustomExportName(false);
    }
    setErrors({});
  }, [account]);

  // Auto-update export display name if not custom
  useEffect(() => {
    if (!customExportName && institutionName && accountName) {
      setExportDisplayName(generateExportDisplayName(institutionName, accountName));
    }
  }, [institutionName, accountName, customExportName]);

  const handleExportDisplayNameChange = (value: string) => {
    setExportDisplayName(value);
    setCustomExportName(true);
  };

  const handleResetExportName = () => {
    setExportDisplayName(generateExportDisplayName(institutionName, accountName));
    setCustomExportName(false);
  };

  const validate = (): boolean => {
    const newErrors: { institutionName?: string; accountName?: string } = {};

    if (!institutionName.trim()) {
      newErrors.institutionName = 'Institution name is required';
    }

    if (!accountName.trim()) {
      newErrors.accountName = 'Account name is required';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    if (!validate()) return;

    onSave({
      institutionName: institutionName.trim(),
      accountName: accountName.trim(),
      exportDisplayName: exportDisplayName.trim() || undefined,
      accountType: accountType || undefined
    });
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white rounded-lg shadow-xl max-w-lg w-full mx-4">
        {/* Modal Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-neutral-200">
          <h3 className="text-lg font-semibold">
            {account ? 'Edit Account' : 'Add Account'}
          </h3>
          <button
            className="text-neutral-400 hover:text-neutral-600 transition-colors"
            onClick={onCancel}
          >
            <FontAwesomeIcon icon={faTimes} />
          </button>
        </div>

        {/* Modal Body */}
        <form onSubmit={handleSubmit}>
          <div className="px-6 py-4 space-y-4">
            {/* Institution Name */}
            <div>
              <label className="block text-sm font-medium text-neutral-700 mb-1">
                Institution Name <span className="text-red-500">*</span>
              </label>
              <input
                type="text"
                className={`electronInput w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                  errors.institutionName ? 'border-red-300' : 'border-neutral-300'
                }`}
                placeholder="e.g., TD Bank, Chase"
                value={institutionName}
                onChange={(e) => setInstitutionName(e.target.value)}
              />
              {errors.institutionName && (
                <p className="text-red-500 text-sm mt-1">{errors.institutionName}</p>
              )}
            </div>

            {/* Account Name */}
            <div>
              <label className="block text-sm font-medium text-neutral-700 mb-1">
                Account Name <span className="text-red-500">*</span>
              </label>
              <input
                type="text"
                className={`electronInput w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                  errors.accountName ? 'border-red-300' : 'border-neutral-300'
                }`}
                placeholder="e.g., Checking, Savings, Sapphire Reserve"
                value={accountName}
                onChange={(e) => setAccountName(e.target.value)}
              />
              {errors.accountName && (
                <p className="text-red-500 text-sm mt-1">{errors.accountName}</p>
              )}
            </div>

            {/* Export Display Name */}
            <div>
              <label className="block text-sm font-medium text-neutral-700 mb-1">
                Export Display Name
              </label>
              <div className="flex gap-2">
                <input
                  type="text"
                  className="electronInput flex-1 px-3 py-2 border border-neutral-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                  placeholder="Auto-generated from institution and account"
                  value={exportDisplayName}
                  onChange={(e) => handleExportDisplayNameChange(e.target.value)}
                />
                {customExportName && (
                  <button
                    type="button"
                    className="px-3 py-2 text-sm text-blue-600 hover:text-blue-700 hover:bg-blue-50 rounded-lg transition-colors"
                    onClick={handleResetExportName}
                    title="Reset to auto-generated name"
                  >
                    Reset
                  </button>
                )}
              </div>
              <p className="text-neutral-500 text-sm mt-1">
                This name appears in exports. Leave blank to auto-generate.
              </p>
            </div>

            {/* Account Type */}
            <div>
              <label className="block text-sm font-medium text-neutral-700 mb-1">
                Account Type
              </label>
              <select
                className="electronInput w-full px-3 py-2 border border-neutral-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                value={accountType}
                onChange={(e) => setAccountType(e.target.value as AccountType | '')}
              >
                <option value="">Select type (optional)</option>
                <option value="checking">Checking</option>
                <option value="savings">Savings</option>
                <option value="credit">Credit</option>
                <option value="investment">Investment</option>
              </select>
            </div>
          </div>

          {/* Modal Footer */}
          <div className="flex justify-end gap-3 px-6 py-4 border-t border-neutral-200 bg-neutral-50 rounded-b-lg">
            <button
              type="button"
              className="px-4 py-2 border border-neutral-200 text-neutral-600 rounded-lg hover:bg-neutral-100 transition-colors"
              onClick={onCancel}
            >
              Cancel
            </button>
            <button
              type="submit"
              className="px-4 py-2 bg-neutral-900 text-white rounded-lg hover:bg-neutral-800 transition-colors"
            >
              {account ? 'Save Changes' : 'Add Account'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default AccountFormModal;
